# Layer message
string laygername

string x_topic   
string x_pos_topic   
string x_neg_topic

string y_topic   
string y_pos_topic   
string y_neg_topic

int32 in_features
int32 out_features
int32 num_epochs
